texto.txt
=> PULL REQUEST RAMA

index.html
=> cambio ezu 21.4

index.html
=> cambio a naranja

index.html
=> rama_brown

index.html
=> agregue verde

index.html
No se como hacer para que cubra todo
=> Agregue fondito

index.html
=> letra acorde fondito

index.html
agrego subtitulo y cambio de color al cuadro
=> agrego subtitulo

index.html, style.css
=> Agregue style

index.html, style.css
=> Agregue boton

index.html
=> reordené jerarquia

index.html, style.css
=> la-calcu-mas-loca

index.html
=> agregue ID

index.html, style.css
=> Insertando chafa a la calcu

style.css
=> agrego el jover

app.js, calculadora.js, index.html
=> Agrego boton dos

app.js, calculadora.js, index.html
Agrego funcion escribirNumerazos
=> Agrego funcion escribirNumerazos

app.js, calculadora.js, index.html, style.css
=> Agrego botonazo reinicio

app.js
Agregue esto por que soy un tipazo
=> Agregue un comentario valioso

app.js
=> hago este commit porque el ridro la cago

style.css
=> v a p o r w a v e 3 p

index.html
=> agregue el carajo

index.html
=> agrego un id poronga

index.html
=> soy un amargo no me gustan los xd

index.html
=> xddddddddddd

index.html
=> hago un cambio serio

style.css
=> gordo que hiciste

index.html, style.css
=> el gordo vapor

style.css
=> chocamo chocamo

index.html, style.css
=> completando la calcu

calculadora.js
=> bjeeep bjeeep bjeeeep
